language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

sudo: false

before_install:
  - sed -i'' -e "s/, ':dummy-android-module'//" settings.gradle
